### ISSUE TITLE
Really need some documentation.

### ISSUE THREAD

**Issue by Magrangs** [carlowahlstedt/NewmanPostman_VSTS_Task#1]
Some documentation on how to use this as part of the build/release process is essential.

**Comment by carlowahlstedt** [comment]
Thanks for the comment. I am looking to work on that. I got a PoC working with the limited set of parameters I needed from Newman. I'm hoping to add documentation as well as add more the newman parameters.

In the meantime, I can tell you the parameters that are currently supported:

- Collection File Source
- Environment
- SSL Client Cert
- SSL Client Key
- Reporter Html Template
- Reporters

Are there others that would benefit you?

**Comment by carlowahlstedt** [comment]
I've updated the [readme](https://github.com/carlowahlstedt/NewmanPostman_VSTS_Task/blob/master/README.md) to show the fields that are currently used (listed in the comment above) but in image form. I've also noted that this task will not install newman and it must otherwise be installed on the build agent.

If there are other specific parameters to newman that you'd like to see supported please let me know. Thanks.

**Comment by Magrangs** [comment]
Great many thanks!
