### ISSUE TITLE
Unable to pass -k --insecure option via TFS plugin

### ISSUE THREAD

**Issue by srini4code** [carlowahlstedt/NewmanPostman_VSTS_Task#4]
Hi Carlo,

I downloaded and configured the NewmanPostman_VSTS_Task, I stored the postman collection.json file in TFS and using it to run in my build pipeline. It works fine from my command line (both locally and via TFS agent), however i'm unable to pass the parameter "-k" for ignoring the SSL from the plugin.

newman run postman_collection.json -k

Can you please advice if there is anyway I can pass the -k option via plugin?

**Comment by carlowahlstedt** [comment]
Sorry, I saw this over the holiday but was busy and forgot about it.

That can be added as a parameter to the task. That's the best way to make this available. It would require a code change to the extension. Feel free to send a PR and I'll look at it. Otherwise, next time I get a chance I'll add it in.

Thanks.

**Comment by carlowahlstedt** [comment]
Disable strict SSL option as been added and release.

Please [leave an extension review](https://marketplace.visualstudio.com/items?itemName=carlowahlstedt.NewmanPostman) if you find it useful.

Thanks!

**Comment by Srinu3366** [comment]
I will try using this and post an update here.
