### ISSUE TITLE
Adding multiple 'Newman the cli Companion for Postman' tasks causes a persistent prompt to save

### ISSUE THREAD

**Issue by frankvaneykelen** [carlowahlstedt/NewmanPostman_VSTS_Task#73]
When I add a second 'Newman the cli Companion for Postman' to my build - for example by cloning the first one - and click 'Save' (or 'Save & queue') the 'Save' (and 'Save & queue') buttons are not greyed out afterwards, even though my changes have been persisted. Reloading the edit build page causes a "This page is asking you to confirm that you want to leave - data you have entered may not be saved." prompt too, and after reloading the page still thinks there are unsaved changes.

**Azure DevOps Version:**
 - Installation: on premises Microsoft Visual Studio Team Foundation Server Version 15.117.27414.0 (Team Foundation Server 2017 Update 3)
 - Task Version: 4

**Comment by frankvaneykelen** [comment]
Just did a test: this is not an issue on Azure DevOps (https://dev.azure.com)

**Comment by carlowahlstedt** [comment]
@frankvaneykelen sorry, but I can't be much help here as I don't have any versions of on-prem installed. It does look like you're using a pretty old version, so I would suggest updating or requesting that it be updated as you'll gain a lot out of the update beyond a bug fix for something like this. For security reasons, the task had to be updated to the latest version of the task library and that could be causing the issue here, but it's more than I can troubleshoot.
